chore(styling): tidy styles for tables
konveyor/forklift-ui pull request #623
Opened 2021-06-03 18:11 UTC by seanforyou23

This PR applies some styling enhancement to various tables in the UI. I tried to fine-tune them as best I could without making major changes to the way the data is output. It's not perfect in the sense that at certain viewport widths, the rows still slightly overflow their container, but it's to a lesser degree now.

### Before/after Migration details table:
<img width="420" alt="Screen Shot 2021-06-03 at 1 23 36 PM" src="https://user-images.githubusercontent.com/5942899/120690104-cb3cb000-c472-11eb-8236-b136b67f737e.png">

<img width="420" alt="Screen Shot 2021-06-03 at 1 23 16 PM" src="https://user-images.githubusercontent.com/5942899/120690101-cb3cb000-c472-11eb-9b38-99dd76a74a60.png">

### Before/after Providers table:
<img width="420" alt="Screen Shot 2021-06-02 at 2 34 43 PM" src="https://user-images.githubusercontent.com/5942899/120690283-0212c600-c473-11eb-89b3-d7073df8f8fd.png">

<img width="420" alt="Screen Shot 2021-06-02 at 2 34 14 PM" src="https://user-images.githubusercontent.com/5942899/120690282-0212c600-c473-11eb-801a-ca960f78556b.png">

Steps toward resolving https://github.com/konveyor/forklift-ui/issues/168 and https://github.com/konveyor/forklift-ui/issues/217

2021-06-07 10:33 UTC, gildub requested changes
Looks good.

Just a minor formating error which makes CI fails, a missing comma on line 11 of /home/runner/work/forklift-ui/forklift-ui/src/app/Providers/components/VMwareProviderHostsTable/VMwareProviderHostsTable.tsx

2021-06-08 13:13 UTC, gildub commented
@seanforyou23, thanks, could you please rebase to update branch.

2021-06-08 16:13 UTC, mturley requested changes
Nice work man, it's looking better. I do think there's some odd stuff going on with vertical spacing though. In various tables we have cell contents that are positioned at the top or bottom of the cell instead of the center of the cell. At the very least they should all be consistent in each table (the openshift providers table has some columns misaligned with others) but ideally all the contents within the red lines here should have the same amount of space above and below them in their cell:

![Screen Shot 2021-06-08 at 12 06 21 PM](https://user-images.githubusercontent.com/811963/121220431-981f6580-c852-11eb-9528-c6a51d0b520a.png)

![Screen Shot 2021-06-08 at 12 08 06 PM](https://user-images.githubusercontent.com/811963/121220446-9a81bf80-c852-11eb-848b-61eb3c9a2959.png)

I'm realizing that part of this was already an issue (https://github.com/konveyor/forklift-ui/issues/179) but I think it's worth fixing while we're in here.

Also on the Plans page, the Progress column looks a bit odd with more space between the progress bar and its label than above and below the bar. I think that's one table that we can maybe leave in non-compact form. The migration details table and mappings table might also have been fine non-compact, it was mostly the providers tables that needed the extra space. What do you think @vconzola ?

2021-06-08 16:13 UTC, mturley commented on src/app/Providers/components/ProvidersTable/OpenShift/OpenShiftProvidersTable.tsx
> +      <Level className="pf-u-pb-sm">
Not that it matters much but I think we can import this class from `'@patternfly/react-styles/css/utilities/Spacing/spacing'` like we do elsewhere

2021-06-08 20:00 UTC, mturley commented
Thanks! Hm, @vconzola what do you think about the text in the rows of the migration details page? I was imagining we wanted the contents of the cells all to be vertically centered (so the column with the pipeline dots would have its text higher than the columns that don't have content under the text) but as it is currently, the text is all aligned and it just looks like all the other columns have blank space lined up with the pipeline dots.

2021-06-08 20:27 UTC, vconzola commented
@mturley You're correct. My intention was that cell contents be center aligned vertically even if it means the text above the pipeline isn't exactly in line with the text in other cells. Just a personal preference - I think it looks better this way.

2021-06-08 22:05 UTC, seanforyou23 commented
There are a few different ways we could go about implementing the vertical alignment for the various data cells and I felt this PR start to grow - if you're cool with it I'd like to break that out into a follow-up PR to keep it manageable from a review standpoint.

2021-06-09 14:50 UTC, mturley commented
Looks like there are some merge conflicts now... sorry, I probably should have merged this ahead of #597 and fixed them on my end. Let me know if you want a hand.

2021-06-09 15:55 UTC, seanforyou23 commented
All good - I rebased and went ahead and gave the Red Hat Virtualization provider table the same treatment.

2021-06-09 17:10 UTC, mturley approved these changes

2021-06-09 17:10 UTC, merged