feat(Mappings): consolidate storage/network mappings pages
konveyor/forklift-ui pull request #626
Opened 2021-06-04 14:25 UTC by seanforyou23

This PR updates the primary nav to go from two sub-menus for the different types of mappings to a single "Mappings" view with tabs for the mapping type options, modeled after the Providers page layout. There shouldn't be any functional changes, but please do test this out as I'm new to the project 😅 

<img width="1000" alt="Screen Shot 2021-06-04 at 10 19 30 AM" src="https://user-images.githubusercontent.com/5942899/120816482-c6cdd100-c51e-11eb-9e11-65d98df9cfab.png">

Should help close https://github.com/konveyor/forklift-ui/issues/112

[issue-112] marry network/storagem mapping pages

2021-06-04 17:55 UTC, vconzola requested changes
@seanforyou23 The only thing I see that looks a little hinky is that the page title changes with tab selection. I think ti should just say "Mappings" all the time. I do like that the context (storage vs. network) is included in the create modals.

2021-06-07 12:26 UTC, gildub reviewed
This looks very good.
I've tested storage and mapping, creation, edition and deletion, it looks and works just fine.
Ready to merge once title issue mentioned by @vconzola is addressed.
Thanks

2021-06-07 17:50 UTC, vconzola reviewed
LGTM. Thanks @seanforyou23 .

2021-06-07 19:05 UTC, vconzola approved these changes

2021-06-08 12:50 UTC, gildub approved these changes

2021-06-08 12:58 UTC, merged