fix(providers): update form field labels for better readability
konveyor/forklift-ui pull request #674
Opened 2021-06-30 19:22 UTC by seanforyou23

This PR updates the form field labels for the add provider modal. For VMware I used the "vCenter" prefix, and for RHV/oVirt I used the respective prefix for those as well. I also changed the helper text for Name/username fields based on some language from the docs, should be a little clearer for users who may be unfamiliar with what some of these properties do.

<img width="400" alt="Screen Shot 2021-07-06 at 12 32 08 PM" src="https://user-images.githubusercontent.com/5942899/124636191-44566b00-de56-11eb-99dd-065d0392f10c.png">

<img width="400" alt="Screen Shot 2021-07-06 at 12 32 15 PM" src="https://user-images.githubusercontent.com/5942899/124636192-44566b00-de56-11eb-99a4-1db027cf3a83.png">

should help close https://github.com/konveyor/forklift-ui/issues/655

2021-07-01 08:54 UTC, apinnick commented on src/app/Providers/components/AddEditProviderModal/AddEditProviderModal.tsx
> +                    label="RHV Manager Hostname or IP address"
Following Patternfly4 and RHV conventions, this should be "RHV Manager host name or IP address"

2021-07-01 08:55 UTC, apinnick commented on src/app/Providers/components/AddEditProviderModal/AddEditProviderModal.tsx
> +                    label="RHV Manager Username"
Change to "RHV Manager user name"

2021-07-01 08:57 UTC, apinnick commented on src/app/Providers/components/AddEditProviderModal/AddEditProviderModal.tsx
> +                    label="RHV Manager Password"
RHV Manager password

2021-07-01 13:13 UTC, mturley commented
@apinnick what about in upstream builds? We're using the oVirt branding on providers instead of RHV when building the UI with Forklift rather than MTV branding. Is "oVirt Manager" still the correct term in that case?

2021-07-01 13:23 UTC, mturley requested changes
@seanforyou23 one current drawback of useFormState is that we have to duplicate the field names in both the schema and the field labels themselves. You'll need to modify these in both places for the validation errors to appear correctly (try focusing and unfocusing a required field to see an example).

In this case, if you look above where we define `const sourceProviderFields` (fields used for both VMware and RHV/oVirt providers), we have `hostnameSchema`. If you go to where that is declared you'll see it's a yup schema with `.label('Hostname or IP address')`, which defines how the field is named in validation error messages.

Since we now need that field to have different labels for the different provider types, what we probably need to do is remove the `.label()` from that imported schema and move `hostname` from `sourceProviderFields` into both the `vsphere: useFormState(...)` and `ovirt: useFormState(...)` below, with separate `hostnameSchema.label(...)`s in there.

Similarly we need to change the `.label()` on the username and password fields used here as well, maybe we need to just get rid of `sourceProviderFields` and have them all defined in both forms.

Left a comment above for Avital about oVirt/RHV branding as well, these labels may need to be conditional based on `ENV.BRAND_TYPE`.

2021-07-01 13:26 UTC, seanforyou23 commented
Super helpful, thx @mturley - I'll make adjustments and send an update soon.

2021-07-01 18:25 UTC, mturley commented
@apinnick should we also put different labels on these fields when adding a VMware provider? They are the same, just "Hostname or IP address", "Username" and "Password".

![Screen Shot 2021-07-01 at 2 24 46 PM](https://user-images.githubusercontent.com/811963/124172747-311f5600-da78-11eb-8919-76474fbe07af.png)

2021-07-01 18:41 UTC, mturley approved these changes
Code LGTM! I'll wait for Avital's answer about VMware, we might as well do this all at once if we need a BZ for each backported PR now.

Also, to follow up later on the label duplication issue, I opened this: https://github.com/konveyor/lib-ui/issues/69

2021-07-04 07:46 UTC, apinnick commented
> @apinnick what about in upstream builds? We're using the oVirt branding on providers instead of RHV when building the UI with Forklift rather than MTV branding. Is "oVirt Manager" still the correct term in that case?

@mturley The correct upstream term for RHV Manager is oVirt Engine.

2021-07-04 07:48 UTC, apinnick commented
> @apinnick should we also put different labels on these fields when adding a VMware provider? They are the same, just "Hostname or IP address", "Username" and "Password".
> 
> ![Screen Shot 2021-07-01 at 2 24 46 PM](https://user-images.githubusercontent.com/811963/124172747-311f5600-da78-11eb-8919-76474fbe07af.png)

@mturley These labels are not correct for VMware. I'm sure that we updated the provider fields a while ago. All lthose fields are for vCenter. That is very important because we don't want the user to mistake "host" for ESXi host.

![image](https://user-images.githubusercontent.com/31725355/124377604-5e0c7c80-dcb5-11eb-814e-edc517c64889.png)

2021-07-04 11:10 UTC, mturley commented
@apinnick 

> These labels are not correct for VMware

Which ones, the ones in my screenshot? I do remember we updated them at some point, but I just wasn't sure if we should give them more specific labels since the equivalent fields for RHV are getting more specific labels.

Those field descriptions are from the documentation, right? Should they also be in the UI under help icons like the name and fingerprint fields?

2021-07-04 11:57 UTC, apinnick commented
@mturley 
> Which ones, the ones in my screenshot? I do remember we updated them at some point, but I just wasn't sure if we should give them more specific labels since the equivalent fields for RHV are getting more specific labels.

It's not so much that they are wrong (I overstated that) but that they needed documentation because users were confused about whether they needed the vCenter or ESXi credentials, etc.

If the fields do not have to be re-used for other providers and if the RHV fields will be specific, I think it makes sense to add "vCenter" to the labels:

- vCenter host name or IP address
- vCenter admin user name
- vCenter admin password

> 
> Those field descriptions are from the documentation, right? 

Yes, that is a screenshot of the user guide. 

> Should they also be in the UI under help icons like the name and fingerprint fields?

If you are not planning to update the field labels, then they should be in the tooltips or help icons. But I think it would be easier for the user if you update the field labels with "vCenter ..."

2021-07-06 16:41 UTC, seanforyou23 commented
@apinnick I pushed some updates and updated the PR description to reflect the latest changes, let me know what you think when you have time to take another look. Thank you!

2021-07-07 15:57 UTC, mturley approved these changes
LGTM, thanks @seanforyou23 !

@apinnick if you have more feedback here we can address it in a followup PR, I just want to move this along.

2021-07-07 15:58 UTC, merged