[QE] Added Modification to Cancel Method
konveyor/forklift-ui pull request #880
Opened 2022-01-05 14:33 UTC by kpunwatk

modified:   pkg/qe-tests/cypress/integration/models/plan.ts
	modified:   pkg/qe-tests/cypress/integration/types/constants.ts
	modified:   pkg/qe-tests/cypress/integration/views/plan.view.ts

2022-01-11 12:49 UTC, kpunwatk commented
@ibragins Please Review the PR

2022-01-17 09:26 UTC, ibragins requested changes

2022-01-17 09:26 UTC, ibragins commented on pkg/qe-tests/cypress/integration/models/plan.ts
> +    cy.get(arrowDropDown).click();
This should be replaced by `click(arrowDropDown)`

2022-01-17 09:28 UTC, ibragins commented
I've asked to change something, also one of the tests is failing

2022-01-25 10:18 UTC, ibragins approved these changes

2022-01-25 10:18 UTC, merged