Bug 2049638: Add tooltip explanation on 'Select migration network' button
konveyor/forklift-ui pull request #928
Opened 2022-02-28 20:34 UTC by mturley

On the VMware Hosts table, when no other tooltip needs to be displayed on the "Select migration network" button (other tooltips are "Select at least one host" or "Selected hosts have no networks in common", the following tooltip will be shown:

![Screen Shot 2022-02-28 at 3 32 39 PM](https://user-images.githubusercontent.com/811963/156054596-a97a6fa4-ef70-41f5-9d89-9709cbf3b749.png)

2022-02-28 20:34 UTC, mturley commented
cc @stoobie

2022-03-01 13:33 UTC, gildub approved these changes
LGTM

2022-03-01 14:50 UTC, stoobie requested changes
Two suggestions.

2022-03-01 14:50 UTC, stoobie commented on pkg/web/src/app/Providers/components/VMwareProviderHostsTable/VMwareProviderHostsTable.tsx
> +                ? 'Selected hosts have no networks in common'
```suggestion
                ? 'Selected hosts have no network in common'
```

2022-03-01 14:50 UTC, stoobie commented on pkg/web/src/app/Providers/components/VMwareProviderHostsTable/VMwareProviderHostsTable.tsx
> +                : 'Select a network for migration data transfer for the selected hosts'
```suggestion
                : 'Select a network for transferring migration data from the selected hosts'
```

2022-03-01 15:37 UTC, merged